### ISSUE TITLE
rJava problem

### ISSUE THREAD

**Issue by lucanard** [c-ruttkies/MetFragR#13]
Hi 

I have been trying to use the metfRag package, but unfortunately when I use the function score.molecules.from.container I alwayas get this error: 
"Error in .jcall(obj, "[Lorg/openscience/cdk/interfaces/IAtomContainer;",  : 
  method generateMatchingFragments with signature ([DDDZII)[Lorg/openscience/cdk/interfaces/IAtomContainer; not found"

I get a very similar error with the function getFragments. I think it is an rJava problem, but I am not able to solve it. Any idea of where this problem arises from?

**Comment by c-ruttkies** [comment]
Hi lucanard,

unless you are still want to use metfRag R package this should be fixed now. You can also use the run.metfrag function to query online databases. The score.molecules.from.container function has a new declaration:

score.molecules.from.container<-function(molecules, mzs, ints, exact.mass,
                                         number.threads=1, mz.abs=0.01,
                                         mz.ppm=10, pos.charge=TRUE,
                                         mode=1, tree.depth=2, score.names=c("FragmenterScore"), scoreWeights=c(1.0))

In case of further problems just let me know.

Best regards,
Christoph

**Comment by lucanard** [comment]
Thank you very much Christoph.
It seems working fine now. Waiting for the release of the manual.
