### ISSUE TITLE
Explained peaks with run.metfrag

### ISSUE THREAD

**Issue by rhelmus** [c-ruttkies/MetFragR#17]
Hi Christoph,

Perhaps I am missing something obvious (it is late), but is `run.metfrag` able report the actual m/z's that were matched besides their scores? In the commandline version the `ExplPeaks` column contains such information.

Thanks,
Rick

**Comment by c-ruttkies** [comment]
Hi Rick,

the ExplPeaks column is currently not in the results of the run.metfrag function. I will include that in the next day. Thanks for the comment.

Best regards,
Christoph

**Comment by rhelmus** [comment]
Thanks! That would be great.

If it's not too much trouble could you also add the `FormulasOfExplPeaks` column?

**Comment by c-ruttkies** [comment]
Hi Rick,
current version update fixes your issue. The properties should now occur in the results lists.
Please close this issue if your fine with it.
Best regards,
Christoph

**Comment by rhelmus** [comment]
Hi Christoph,

Thanks again! The properties are there now.
