### ISSUE TITLE
Can not install R package using command "install_github("c-ruttkies/MetFragR/metfRag")"

### ISSUE THREAD

**Issue by xiaodfeng** [c-ruttkies/MetFragR#22]
I have installed the metfrag R package successfully using the following command before:
library(devtools)
install_github("c-ruttkies/MetFragR/metfRag")

But I can not use the command to install the package any more. I get the following error:

Downloading GitHub repo c-ruttkies/MetFragR@master
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Error exit delayed from previous errors.
Error: Does not appear to be an R package (no DESCRIPTION)

Can you help to solve the issue?

Best regards,
Xiaodong

**Comment by xiaodfeng** [comment]
Problem solved. In case someone may also come across this problem. I share my solution.
Input `Sys.setenv("TAR" = "internal")` in Rstudio. According to the solution in https://github.com/r-lib/devtools/issues/1939.

Then
library(devtools)
install_github("c-ruttkies/MetFragR/metfRag")
Maybe you also need the following command to solve the problem of rJava.
`Sys.setenv(JAVA_HOME='c:\\Program Files\\Java\\jre1.8.0_191')` .

**Comment by sneumann** [comment]
Thanks for sharing the solution. Yours, Steffen
